# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sudoku
      
    ports:
      - 27018:27017
    volumes:
      - ./database/data:/data/db 
      - ./database/init:/docker-entrypoint-initdb.d
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/sudoku?authSource=admin
      ME_CONFIG_BASICAUTH: false
